name: Build Extensions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Create local.properties
        run: echo "sdk.dir=/usr/local/android-sdk" > local.properties

      - name: Build with Gradle (skip lint)
        run: ./gradlew build -x lint

      - name: Prepare build artifacts
        run: |
          mkdir output
          cp -r **/build/outputs/* output/ || true
          cp -r **/build/*.json output/ || true

      - name: Publish to builds branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git fetch origin
          git checkout -B builds
          rm -rf *
          cp -r output/* .
          git add .
          git commit -m "Build artifacts" || echo "No changes to commit"
          git push origin builds --force
